In [1]:
import numpy as np

In [2]:
a=np.arange(15).reshape(3,5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [6]:
a.ndim

2

In [7]:
a.dtype.name

'int64'

In [8]:
a.itemsize

8

In [9]:
a.size

15

In [10]:
type(a)

numpy.ndarray

In [14]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [16]:
#array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.
c= np.array([(1.5,2,3), (4,5,6)])
c

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [17]:
#The type of the array can also be explicitly specified at creation time:
d= np.array( [ [1,2], [3,4] ], dtype=complex )
d

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [18]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [19]:
np.ones((2,3,4))

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [21]:
np.empty((2,4))

array([[ 1.,  0.,  2.,  0.],
       [ 3.,  0.,  4.,  0.]])

In [23]:
# accepts floating numbers also
np.arange(5,30,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29])

In [27]:
np.linspace(2,10,17) 
#17 numbers form 2 to 10

array([  2. ,   2.5,   3. ,   3.5,   4. ,   4.5,   5. ,   5.5,   6. ,
         6.5,   7. ,   7.5,   8. ,   8.5,   9. ,   9.5,  10. ])

In [29]:
x=np.linspace(0,2*np.pi,100)
f=np.sin(x)
f

array([  0.00000000e+00,   6.34239197e-02,   1.26592454e-01,
         1.89251244e-01,   2.51147987e-01,   3.12033446e-01,
         3.71662456e-01,   4.29794912e-01,   4.86196736e-01,
         5.40640817e-01,   5.92907929e-01,   6.42787610e-01,
         6.90079011e-01,   7.34591709e-01,   7.76146464e-01,
         8.14575952e-01,   8.49725430e-01,   8.81453363e-01,
         9.09631995e-01,   9.34147860e-01,   9.54902241e-01,
         9.71811568e-01,   9.84807753e-01,   9.93838464e-01,
         9.98867339e-01,   9.99874128e-01,   9.96854776e-01,
         9.89821442e-01,   9.78802446e-01,   9.63842159e-01,
         9.45000819e-01,   9.22354294e-01,   8.95993774e-01,
         8.66025404e-01,   8.32569855e-01,   7.95761841e-01,
         7.55749574e-01,   7.12694171e-01,   6.66769001e-01,
         6.18158986e-01,   5.67059864e-01,   5.13677392e-01,
         4.58226522e-01,   4.00930535e-01,   3.42020143e-01,
         2.81732557e-01,   2.20310533e-01,   1.58001396e-01,
         9.50560433e-02,

In [30]:
# If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:
print(np.arange(1,10000))

[   1    2    3 ..., 9997 9998 9999]


To disable this behaviour and force NumPy to print the entire array, you can change the printing options using set_printoptions.
. np.set_printoptions(threshold='nan')

### Basic Operations

In [32]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
c=a-b
print(c)
print(b**2)
print(10*np.sin(a))
print(a<35)

[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]


In [33]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )

In [34]:
A*B

array([[2, 0],
       [0, 4]])

In [35]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [36]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

In [45]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
b

array([[ 0.9012195 ,  0.51144924,  0.78915029],
       [ 0.68063124,  0.57650292,  0.93456123]])

In [46]:
a=a*3
b+=a
b

array([[ 3.9012195 ,  3.51144924,  3.78915029],
       [ 3.68063124,  3.57650292,  3.93456123]])

In [47]:
a+=b

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [50]:
c=np.exp(b*1j)
c

array([[-0.72509304-0.68865092j, -0.93237920-0.36148172j,
        -0.79755951-0.60324028j],
       [-0.85820258-0.51331114j, -0.90690785-0.42132902j,
        -0.70173348-0.71243956j]])

In [51]:
c.dtype.name

'complex128'

In [53]:
print(b.sum())
print(b.min())
print(b.max())

22.3935144178
3.51144923773
3.93456122959


In [54]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
a.sum(axis=0) #sum of each column

array([12, 15, 18, 21])

In [56]:
a.max(axis=1) #max of each row

array([ 3,  7, 11])

In [57]:
a.cumsum(axis=0) #cumulative sum of each column

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [62]:
a = np.arange(10)**3
a
print(a[2]) #index-2 element
print(a[2:5]) #index-2 to 5-1
a[:6:2]=-1000 # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
print(a)
print(a[ : :-1]) #reverses a
for i in a:
    print(i**(1/3.))

8
[ 8 27 64]
[-1000     1 -1000    27 -1000   125   216   343   512   729]
[  729   512   343   216   125 -1000    27 -1000     1 -1000]
nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


/home/sridhar/anaconda2/envs/gl-env/lib/python2.7/site-packages/ipykernel/__main__.py:9: RuntimeWarning: invalid value encountered in power


In [63]:
def f(x,y):
    return 10*x+y

In [68]:
b=np.fromfunction(f,(5,4),dtype=int)
print(b)
print(b[2,3])
print(b[0:5,1])
print(b[:,1])
print(b[1:3,:])
print(b[-1])

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]
[40 41 42 43]


In [69]:
#Iterating over multidimensional arrays is done with respect to the first axis:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [70]:
#if one wants to perform an operation on each element in the array, one can use the flat attribute which is an iterator over all the elements of the array:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


# Shape manipulation

## Changing the shape of an array

In [71]:
a = np.floor(10*np.random.random((3,4)))
a

array([[ 4.,  5.,  0.,  0.],
       [ 1.,  5.,  7.,  1.],
       [ 2.,  5.,  6.,  0.]])

In [72]:
a.ravel()

array([ 4.,  5.,  0.,  0.,  1.,  5.,  7.,  1.,  2.,  5.,  6.,  0.])

In [76]:
a.reshape(6,2)#doesn't modfiy the original array

array([[ 4.,  5.],
       [ 0.,  0.],
       [ 1.,  5.],
       [ 7.,  1.],
       [ 2.,  5.],
       [ 6.,  0.]])

In [74]:
a.T

array([[ 4.,  1.,  2.],
       [ 5.,  5.,  5.],
       [ 0.,  7.,  6.],
       [ 0.,  1.,  0.]])

In [75]:
a.T.shape

(4, 3)

In [79]:
a.resize(2,6) #modifies original array
a

array([[ 4.,  5.,  0.,  0.,  1.,  5.],
       [ 7.,  1.,  2.,  5.,  6.,  0.]])

## Stacking together different arrays

In [80]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(a)
print(b)

[[ 5.  1.]
 [ 8.  1.]]
[[ 8.  4.]
 [ 8.  0.]]


In [82]:
np.vstack((a,b))

array([[ 5.,  1.],
       [ 8.,  1.],
       [ 8.,  4.],
       [ 8.,  0.]])

In [83]:
np.hstack((a,b))

array([[ 5.,  1.,  8.,  4.],
       [ 8.,  1.,  8.,  0.]])

The function column_stack stacks 1D arrays as columns into a 2D array

In [84]:
np.column_stack((a,b))   # With 2D arrays

array([[ 5.,  1.,  8.,  4.],
       [ 8.,  1.,  8.,  0.]])

In [90]:
a = np.array([4.,3.])
b = np.array([2.,8.])

In [91]:
from numpy import newaxis
a[:,newaxis]

array([[ 4.],
       [ 3.]])

In [92]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[ 4.,  2.],
       [ 3.,  8.]])

In [93]:
np.vstack((a[:,newaxis],b[:,newaxis]))

array([[ 4.],
       [ 3.],
       [ 2.],
       [ 8.]])

In [94]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

## Splitting one array into several smaller ones

In [96]:
a = np.floor(10*np.random.random((2,12)))
a

array([[ 7.,  6.,  1.,  0.,  6.,  9.,  9.,  4.,  6.,  6.,  8.,  3.],
       [ 9.,  4.,  6.,  9.,  9.,  4.,  9.,  3.,  0.,  7.,  2.,  6.]])

In [97]:
np.hsplit(a,3)   # Split a into 3

[array([[ 7.,  6.,  1.,  0.],
        [ 9.,  4.,  6.,  9.]]), array([[ 6.,  9.,  9.,  4.],
        [ 9.,  4.,  9.,  3.]]), array([[ 6.,  6.,  8.,  3.],
        [ 0.,  7.,  2.,  6.]])]

In [98]:
np.hsplit(a,(3,4)) # Split a after the third and the fourth column

[array([[ 7.,  6.,  1.],
        [ 9.,  4.,  6.]]), array([[ 0.],
        [ 9.]]), array([[ 6.,  9.,  9.,  4.,  6.,  6.,  8.,  3.],
        [ 9.,  4.,  9.,  3.,  0.,  7.,  2.,  6.]])]

# Copies and Views

## No Copy at All

In [99]:
a = np.arange(12)
b = a            # no new object is created
print(b is a)          # a and b are two names for the same ndarray object
b.shape = 3,4    # changes the shape of a
a.shape

True


(3, 4)

In [100]:
def f(x):
    print(id(x))

In [102]:
id(a)                           # id is a unique identifier of an object

140160687847184

In [103]:
f(a)

140160687847184


## View or Shallow Copy

In [104]:
c = a.view()
print(c is a)
print(c.base is a)                       # c is a view of the data owned by a
print(c.flags.owndata)
c.shape = 2,6                      # a's shape doesn't change
print(a.shape)
c[0,4] = 1234                      # a's data changes
print(c)
print(a)

False
True
False
(3, 4)
[[   0    1    2    3 1234    5]
 [   6    7    8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


In [105]:
s = a[ : , 1:3]     # spaces added for clarity; could also be written "s = a[:,1:3]"
s[:] = 10           # s[:] is a view of s. Note the difference between s=10 and s[:]=10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

## Deep Copy

In [106]:
d = a.copy()                          # a new array object with new data is created
print(d is a)
print(d.base is a)                          # d doesn't share anything with a
d[0,0] = 9999
a


False
False


array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

# Fancy indexing and index tricks

## Indexing with Arrays of Indices

In [107]:
a = np.arange(12)**2                       # the first 12 square numbers
i = np.array( [ 1,1,3,8,5 ] )

In [108]:
a[i]

array([ 1,  1,  9, 64, 25])

In [109]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )      # a bidimensional array of indices
a[j] 

array([[ 9, 16],
       [81, 49]])

In [110]:
palette = np.array( [ [0,0,0],                # black
                     [255,0,0],              # red
                     [0,255,0],              # green
                    [0,0,255],              # blue
                    [255,255,255] ] )       # white
image = np.array( [ [ 0, 1, 2, 0 ],           # each value corresponds to a color in the palette
[ 0, 3, 4, 0 ]  ] )
palette[image]                            # the (2,4,3) color image

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [111]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
i = np.array( [ [0,1],                        # indices for the first dim of a
               [1,2] ] )
j = np.array( [ [2,1],                        # indices for the second dim
                [3,3] ] )

In [113]:
a[i,j]

array([[ 2,  5],
       [ 7, 11]])

In [114]:
a[i,2]

array([[ 2,  6],
       [ 6, 10]])

In [115]:
a[:,j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [116]:
l = [i,j]
a[l]

array([[ 2,  5],
       [ 7, 11]])

In [117]:
s = np.array( [i,j] )
a[s]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [118]:
a[tuple(s)]

array([[ 2,  5],
       [ 7, 11]])

In [119]:
time = np.linspace(20, 145, 5)                 # time scale
data = np.sin(np.arange(20)).reshape(5,4) 

In [120]:
time

array([  20.  ,   51.25,   82.5 ,  113.75,  145.  ])

In [121]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [123]:
ind = data.argmax(axis=0) # index of the maxima for each series
ind

array([2, 0, 3, 1])

In [124]:
time_max = time[ ind]                       # times corresponding to the maxima
data_max = data[ind, xrange(data.shape[1])]  # => data[ind[0],0], data[ind[1],1]

In [125]:
time_max

array([  82.5 ,   20.  ,  113.75,   51.25])

In [126]:
data_max

array([ 0.98935825,  0.84147098,  0.99060736,  0.6569866 ])

In [127]:
np.all(data_max == data.max(axis=0))

True

In [128]:
a = np.arange(5)
a[[1,3,4]] = 0
a

array([0, 0, 2, 0, 0])

In [129]:
#when the list of indices contains repetitions, the assignment is done several times, leaving behind the last value:
a = np.arange(5)
a[[0,0,2]]=[1,2,3]
a

array([2, 1, 3, 3, 4])

In [130]:
a = np.arange(5)
a[[0,0,2]]+=1
a

array([1, 1, 3, 3, 4])

## Indexing with Boolean Arrays

In [132]:
a = np.arange(12).reshape(3,4)
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [133]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [134]:
a[b]=0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

# The ix_ function

In [135]:
a = np.array([2,3,4,5])
b = np.array([8,5,4])
c = np.array([5,4,6,8,3])

In [136]:
ax,bx,cx = np.ix_(a,b,c)

In [137]:
ax

array([[[2]],

       [[3]],

       [[4]],

       [[5]]])

In [138]:
bx

array([[[8],
        [5],
        [4]]])

In [139]:
cx

array([[[5, 4, 6, 8, 3]]])

In [140]:
ax.shape, bx.shape, cx.shape

((4, 1, 1), (1, 3, 1), (1, 1, 5))

In [142]:
result = ax+bx*cx
result

array([[[42, 34, 50, 66, 26],
        [27, 22, 32, 42, 17],
        [22, 18, 26, 34, 14]],

       [[43, 35, 51, 67, 27],
        [28, 23, 33, 43, 18],
        [23, 19, 27, 35, 15]],

       [[44, 36, 52, 68, 28],
        [29, 24, 34, 44, 19],
        [24, 20, 28, 36, 16]],

       [[45, 37, 53, 69, 29],
        [30, 25, 35, 45, 20],
        [25, 21, 29, 37, 17]]])

In [143]:
result[3,2,4]

17

In [144]:
a[3]+b[2]*c[4]

17

# Simple array operations

In [145]:
import numpy as np
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)

[[ 1.  2.]
 [ 3.  4.]]


In [146]:
a.transpose()

array([[ 1.,  3.],
       [ 2.,  4.]])

In [147]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [148]:
u = np.eye(2)
u

array([[ 1.,  0.],
       [ 0.,  1.]])

In [149]:
np.trace(u)

2.0

In [150]:
y = np.array([[5.], [7.]])

In [151]:
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [152]:
np.linalg.eig(j)

(array([ 0.69722436,  4.30277564]), array([[-0.60889368, -0.3983218 ],
        [ 0.79325185, -0.91724574]]))

In [ ]:
## Automatic Reshaping

In [153]:
a = np.arange(30)
a.shape = 2,-1,3  # -1 means "whatever is needed"
a.shape

(2, 5, 3)